// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MCiv-gS8ROt0wfW51OfmgP-MPjbOawQ',
    appId: '1:837101115572:web:07bc30a991255954491fe1',
    messagingSenderId: '837101115572',
    projectId: 'ecommerce-cf24b',
    authDomain: 'ecommerce-cf24b.firebaseapp.com',
    storageBucket: 'ecommerce-cf24b.appspot.com',
    measurementId: 'G-KN9HCWHZH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhtE7FSnO55DXM6o2os-n4-nwIHK5A3w',
    appId: '1:837101115572:android:35c31f976af4bb99491fe1',
    messagingSenderId: '837101115572',
    projectId: 'ecommerce-cf24b',
    storageBucket: 'ecommerce-cf24b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVW-Tl0vBxUl2jvpswcKdCt6qRf8ht2E',
    appId: '1:837101115572:ios:d095bc348687cb51491fe1',
    messagingSenderId: '837101115572',
    projectId: 'ecommerce-cf24b',
    storageBucket: 'ecommerce-cf24b.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVW-Tl0vBxUl2jvpswcKdCt6qRf8ht2E',
    appId: '1:837101115572:ios:88081fbcf55481da491fe1',
    messagingSenderId: '837101115572',
    projectId: 'ecommerce-cf24b',
    storageBucket: 'ecommerce-cf24b.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
